#!/usr/bin/env bash

# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

AWS_REGION=us-east-1
STACK_NAME=VPC-Test

aws cloudformation delete-stack \
                     --stack-name ${STACK_NAME} \
                     --region ${AWS_REGION}

aws cloudformation wait stack-delete-complete --stack-name ${STACK_NAME} --region ${AWS_REGION}
